[package]
name = "ropk-fw"
version = "0.1.0"
edition = "2024"
description = "Firmware" 

[[bin]]
name = "ropk-fw"
test = false
bench = false

[dependencies]
ropk-radio = { path = "../ropk-radio" }
ropk-usb = { path = "../ropk-usb" }
embassy-executor = { version = "0.8", features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.4", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-nrf = { version = "0.6", features = ["nrf52840", "time-driver-rtc1", "gpiote", "defmt", "unstable-pac"] }
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
defmt = "1"
defmt-rtt = "1"
panic-probe = { version = "1", features = ["print-defmt"] }
embassy-usb = { version = "0.6.0", features = ["defmt", "usbd-hid"] }
usbd-hid = { version = "0.10.0", default-features = false }
static_cell = "2.1.1"
heapless = "0.9.3"

[profile.release]
debug = 2
lto = true
opt-level = "s"

[profile.dev]
debug = 2
opt-level = 1
